[package]
name = "touchpoints"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "6.1.2"
regex = "1.5"
once_cell = "1.7.0"
thiserror = "1.0.24"
